Update crypto_update.yml

diff --git a/.github/workflows/crypto_update.yml b/.github/workflows/crypto_update.yml
--- a/.github/workflows/crypto_update.yml
+++ b/.github/workflows/crypto_update.yml
@@ -19,14 +19,21 @@ jobs:
         python-version: '3.12'
 
     - name: Install Dependencies
-      run: |
-        pip install -r requirements.txt
+      run: pip install -r requirements.txt
 
-    - name: Check environment variables
-      run: echo "GCP_SERVICE_ACCOUNT is set"
+    - name: Check Environment Variables
+      run: |
+        if [[ -z "$GCP_SERVICE_ACCOUNT" ]]; then
+          echo "❌ ERROR: GCP_SERVICE_ACCOUNT is missing!"
+          exit 1
+        else
+          echo "✅ GCP_SERVICE_ACCOUNT is set."
+          echo $GCP_SERVICE_ACCOUNT | base64 --decode | jq .
+        fi
       env:
         GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
+
     - name: Run Crypto Data Script
       env:
-        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}  # Use the GitHub Secret
+        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
       run: python script.py
